### ISSUE TITLE
Please update the 'latest' label correctly

### ISSUE THREAD

**Issue by YvesHertoghs** [BroadbandForum/obbaa#1]
Hi, when creating a new build, could you update the 'latest' label so images can be upgraded in a more efficient manner ?

**Comment by selvaitech** [comment]
new tag with name "latest" is added to obbaa repo. can you please check and confirm the same?

**Comment by YvesHertoghs** [comment]
Still doesn’t seem to work:

root@photon-baa-host [ ~ ]# docker pull broadbandforum/baa
Using default tag: latest
Error response from daemon: manifest for broadbandforum/baa:latest not found
root@photon-baa-host [ ~ ]# docker pull broadbandforum/baa:R2.1.0
R2.1.0: Pulling from broadbandforum/baa
Digest: sha256:8389caebba0b741d447cc18eacdc21c001d8ec361d500d388efd23bad6361280
Status: Image is up to date for broadbandforum/baa:R2.1.0
root@photon-baa-host [ ~ ]#

**Comment by wlupton** [comment]
I think @YvesHertoghs is talking about a DockerHub tag, not a GitHub tag.

**Comment by selvaitech** [comment]
@YvesHertoghs , we have added a new tag "latest" for baa's docker image. the same can be pulled from DockerHub.

Sample logs:

docker pull broadbandforum/baa
Using default tag: latest
latest: Pulling from broadbandforum/baa
1160f4abea84: Already exists 
b1b3e089ad5b: Already exists 
4220f7d94f04: Already exists 
9793ccf5738e: Pull complete 
ebc985c45df6: Pull complete 
a1c7c4a8ebee: Pull complete 
a9e632a78e19: Pull complete 
1bb9136b52dc: Pull complete 
8311fd1b26dc: Pull complete 
Digest: sha256:8389caebba0b741d447cc18eacdc21c001d8ec361d500d388efd23bad6361280
Status: Downloaded newer image for broadbandforum/baa:latest

**Comment by YvesHertoghs** [comment]
works now!
