### ISSUE TITLE
Can't build example Vendor Device Adapters

### ISSUE THREAD

**Issue by krzychu-89** [BroadbandForum/obbaa#2]
Basend on obbaa instruction, section: Creation and Deployment of Vendor Device Adapters

both protocol-translation-example and protocol-translation-snmp can't be build,
when running:
`mvn clean install`
following error is received
`[ERROR] Plugin org.broadband-forum.obbaa:baa-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.broadband-forum.obbaa:baa-maven-plugin:jar:3.0.0: Could not find artifact org.broadband-forum.obbaa:baa-maven-plugin:pom:3.0.0 in opendaylight-release (http://nexus.opendaylight.org/content/repositories/opendaylight.release/) -> [Help 1]`

**Comment by selvaitech** [comment]
@krzychu-89, You need to build obbaa-netconf-stack & obbaa repo if you want to build any submodule of obbaa. 

Can you please help to run(mvn clean install) inside the directory obbaa-netconf-stack & obbaa then attempt to build the adapters - protocol-translation-example and protocol-translation-snmp?
