### ISSUE TITLE
Not able to build obbaa code

### ISSUE THREAD

**Issue by BinayKapri** [BroadbandForum/obbaa#5]
Cloned obbaa code from git clone https://github.com/BroadbandForum/obbaa.git
change directory obbaa
mvn clean install -DskipTests.

Getting below error while building obbaa code .
Failed to execute goal on project device-manager-entities:

Failed to read artifact descriptor for org.broadband.forum.obbaa.netconf:netconf-server-modelnode-fwk:jar3.0.0 ...
Transfer failed for http://repo.boundlessgeo.com/main/org/broadband-forum/obbaa/netconf/netconf-server-modelnode-fwk/3.0.0/netconf-server-modelnode-fwk-3.0.0.pom : Unknown host repo.boundlessgeo.com: Name or service not known

it seems repo.boundlessgeo.com is unavailable?

**Comment by selvaitech** [comment]
@BinayKapri , Can you please confirm if you have cloned & built obbaa-netconf-stack before building obbaa?
 [here ](https://obbaa.broadband-forum.org/installing/env/#env) is the documentation on compilation of dependency repos and obaa.

request you to follow the procedure mentioned.

**Comment by BinayKapri** [comment]
Thanks Selvaraj Ramasamy. i am able to build obbaa repo.
