### ISSUE TITLE
Device simulator is not getting connected/aligned to OB-BAA , throws javax.net.ssl.SSLException: Received fatal alert:handshake_failure.

### ISSUE THREAD

**Issue by BinayKapri** [BroadbandForum/obbaa#6]
Complied and Deployed OB-BAA in Ubuntu 18.04 successfully.
Installed Netconf Device simulator(built from the source code in the legacy branch) as per instruction mentioned in "https://obbaa.broadband-forum.org/installing/sim/#sim".
Create TLS Certificate using ./generateDeviceDuidTLSFiles.sh DPU1
Using netopeer2-cli configure call home.

=========================================
Load private key using below request
=========================================

<?xml version="1.0" encoding="UTF-8"?>
<action xmlns="urn:ietf:params:xml:ns:yang:1">
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
<private-keys>
<load-private-key>
<name>DPU_server_key</name>
<private-key>MIIEowIBAAKCAQEAsRQ1z1Q656qXZgZNpe6PV21kNMJfV8NVUidzKZTRD/uETTFG
nUIXUWdWHy0B5j6YvDCKQfvAspQC9AJdlKpzU7ylJ3SuDhj5R8kGxVM7nylVimNS
T8mRy7yIVgFnoixP5Z662ghCyrWCTYhyekrQf3H+tnWac8fqRtGYJbBVGOHIlXvW
J5ixZUtOni06jt9EdxDzDl98kaDMZ3nlDVSSMWAZdAim4i4D4EhQQQHeY/hF4a19
NE1lFpV1ejk+PEmrjljBgN5AgEH8klko2G1lqxIxuQ8s40+YekWM63vCsiw1cwOk
aKzxz7HSIuW1j1BqfoEh3/7NS1J7BPXBpUqT4wIDAQABAoIBACKcCZxZIR4wWGDn
cHuy8a8rwT8SkmHr2pww+7Av1uChzwzrSZro1PfjE5EKUem3aFC3x/33f4UnqqAY
akPpQJsoLrtUccRtmyMtpjYg+3EzOfXPTcIsamOAmMD+i0vGD2OYr3p3zN4jtbED
ryQ5xSBznk35FFP2ydJHms4a9bbj7vlaa8LF27s0bkPXESJgwRbp4sjDjsyjg6qX
blN54gvmjF2+FZksXqycfM8RDhX2ijVa51e4HBIIGJaxKGVKDcwA/y+0KQ83w+RG
jyggAtFnYSJe/Nr5FBdwOf6CwdFrwQYpxKIGCmd4mznC3kaQLuxYdShfy/Xsx4zU
Vs5ahukCgYEA2d04ngH9tpaAsnQCHtZ1He/nr3BFd16dpHSa5nk+6e0IQLPK9A5+
VL3ghl8q2uYs3jiOkRdCviT55U6AqG3owMni2ierPMA+cIMPMz/5mooCzExWPRMo
s9UTYSE98XHEuJ6EXZ0N8g3vi9HorMiZy0lJAnhgMQN2hqPbDdGnw80CgYEA0BNZ
wt2QTBHC2JjIsq9xdL1X9RRufVnRmtNpR2OdT7vJipmegO/TveeGCfdOufZ1Cs7a
HeLQQeRaiVb+5NyUYRAmxomZKuUcfMUIN4kUa/Kg+6n/M+0NjLd/KxNlH4hxMR/8
/gK/tR5+VBls9HEf1pQQntGLxuqR6ss7XeStZm8CgYEAl40Y9mliKWJ2ciza0MLU
Q5gALf1GhWwO8zieDFcpWaamiAPJ2Y4/eQmAp1iKQi295nOnUOzCY+zq3QWH4CJc
t8d4g9L2flMo3DF/IGKPal445g7wKpoqRTaivX1XTp6afubeIxS+f7QL/9JsLc15
ln0LSamdGFtVVwGivvEp570CgYBso83YCqsOrK9ZO9x+P1AzrbDBC5vs4vqnpf5w
AbjfKqM+NJsnoxChNMMtbOyz99SAgiQsOoKWBM6oqr2HbQwj6bT1MF7CoMFQ++cg
Z/g7rIEVJVtUF09dy2kgao3/+tNu3M7RKUpDHNrEuknDD1WaSdCru6kJgOwS9W3X
xlArDQKBgDEblrCDFn5XtmguQE1PNNPSZuQNA2LhFgLU35I4WBb/1+sCmYMFzy/6
f5XzevVLiK1/TIpxkoX3Tiv+f+yA3WRHnAB8wxmjBmEG/aJcVTUrTpmNSR0Orp1v
udPE1tEZ4w+M64cf25pNhvjIH6+K4w06gJR5thWdclbcPZFvEQ30</private-key>
</load-private-key>
</private-keys>
</keystore>
</action>

========================================
load the certificate and trust chains for the DPU server 
========================================

<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
<private-keys>
<private-key>
<name>DPU_server_key</name>
<certificate-chains>
<certificate-chain>
<name>DPU_server_cert</name>
<certificate>MIIDAzCCAesCCQDXuKt20sxNvDANBgkqhkiG9w0BAQsFADA5MQswCQYDVQQGEwJJ
TjELMAkGA1UECAwCS0ExDDAKBgNVBAcMA0JMUjEPMA0GA1UECgwGT0ItQkFBMCAX
DTIwMDgwOTEwNDgyOFoYDzMzODkwNzIzMTA0ODI4WjBMMQswCQYDVQQGEwJJTjEL
MAkGA1UECAwCS0ExDDAKBgNVBAcMA0JMUjEOMAwGA1UECgwFT0JCQUExEjAQBgNV
BAMMCURVSUQvRFBVMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALEU
Nc9UOueql2YGTaXuj1dtZDTCX1fDVVIncymU0Q/7hE0xRp1CF1FnVh8tAeY+mLww
ikH7wLKUAvQCXZSqc1O8pSd0rg4Y+UfJBsVTO58pVYpjUk/Jkcu8iFYBZ6IsT+We
utoIQsq1gk2IcnpK0H9x/rZ1mnPH6kbRmCWwVRjhyJV71ieYsWVLTp4tOo7fRHcQ
8w5ffJGgzGd55Q1UkjFgGXQIpuIuA+BIUEEB3mP4ReGtfTRNZRaVdXo5PjxJq45Y
wYDeQIBB/JJZKNhtZasSMbkPLONPmHpFjOt7wrIsNXMDpGis8c+x0iLltY9Qan6B
Id/+zUtSewT1waVKk+MCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAiXe18ZUG/Xct
LxWh/CieAylHEbO9yWHuoT8L5bPQAllliQISN6NPjH8h5CyxKY9f30mEPEBDjqob
4U3ddx6irFsonYmNUGboRc4D488UzfGEOlnU3KshaSNkBXngOGTJ7mv+FJfo9p0F
Uv6AOHfv8x/s7z79ihdl0eQ0ElF4shs6T/5VVt55xpEqVEm0PkjnQHvn7hyLc6Io
Y9R6GWYIGi6I1HyiNIG5tX3wKn3/sJSc/dvGjRPv6VXhZzKxSWO1QjHaw7Dtf0qK
b28nJy9LWnWvzT7IvX4MIWYuMIFrLW446KZt5fiVKM8Ej9kV/USL8YrVq/TyT0nG
s7XIb9MMbw==</certificate>
</certificate-chain>
</certificate-chains>
</private-key>
</private-keys>
<trusted-certificates>
<name>DPU_trusted_ca_list</name>
<trusted-certificate>
<name>test_ca</name>
<certificate>MIIDRTCCAi2gAwIBAgIJAL6nrHtB9RlEMA0GCSqGSIb3DQEBCwUAMDkxCzAJBgNV
BAYTAklOMQswCQYDVQQIDAJLQTEMMAoGA1UEBwwDQkxSMQ8wDQYDVQQKDAZPQi1C
QUEwHhcNMTgwNzEwMDQyODUwWhcNMjEwNDI5MDQyODUwWjA5MQswCQYDVQQGEwJJ
TjELMAkGA1UECAwCS0ExDDAKBgNVBAcMA0JMUjEPMA0GA1UECgwGT0ItQkFBMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuV1gWjWTXFWCbBCYe8vkt3Wb
KQWazG1CaJdCE+HMem62dUGSNyN29N6OdoaPot3eEzBNbiox+N3aSkX6+5078px4
GkxKDTiQf4Tw119g7JICDCD4YeYzYUat35N3XsLsrL9ua8svfDCn7UNxasI29HsX
60vH7ip9F9Mh+BvA0k8f++6ylXeNJbu5Re7pyMt9y5E6W0WOGOnvOrmj546QhshL
PtMin0+VaYfOu6p/YOOIdfadjv5i3zxeD+MGUO8F0Vv1NLTv+DpxzldK9gMlLaud
+WzZqMyrnFu3qlnYRej6dq171BiNtBc0ebJl8bbHl/8vlfWIE/oOUv8sPvd4QwID
AQABo1AwTjAdBgNVHQ4EFgQUbRVtFVtOGue/yIfclQ9cEOzhpBkwHwYDVR0jBBgw
FoAUbRVtFVtOGue/yIfclQ9cEOzhpBkwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B
AQsFAAOCAQEAjJ/qvSXreYE2AGs8tZ121ubk+laD+ADpq+EtvpVpkCcGHKGSSGvW
4r1wDtrMGKLKKzwMIkFIK1Bwka5bIC5Jo7c/oRVt1djVScSkCmL/4z4fGRei5iGy
FK6hTTtDfoxvht+/ILEeOFsDTJSWMHFOfjkdH/DKekrS03wqS9GVawUZboRaoSi3
c110ZSJag2QcyveWbvRbMTvk1jjoPakTnFK7HTiTv+XxheLJL4WOn1Mhj+iksP/v
ZFs7XY38w/1AgA8gGGh9exfD28MpxjnO+xAgkTufuW+KB+82lXf1geoCzGoV7S2R
KBKGYUlmDh7SJaQO0x3fGwFz84IQhgZvxA==</certificate>
</trusted-certificate>
</trusted-certificates>
</keystore>

==================================================
Enable callhome 
==================================================
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>default-client</name>
      <tls>
        <endpoints>
          <endpoint>
            <name>default-tlsc</name>
            <address>172.18.0.2</address>
            <port>4335</port>
          </endpoint>
        </endpoints>
        <certificates>
          <certificate>
            <name>DPU_server_cert</name>
          </certificate>
        </certificates>
        <client-auth>
          <trusted-ca-certs>DPU_trusted_ca_list</trusted-ca-certs>
          <cert-maps>
            <cert-to-name>
              <id>1</id>
    <fingerprint>4D:7D:F0:3A:C7:07:B1:66:E7:A0:62:A6:88:7A:A9:BF:0A:53:CC:13:BD:4A:9B:1B:9D:97:3C:FF:5A:C3:8E:A7</fingerprint>
              <map-type xmlns:x509c2n="urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name">x509c2n:specified</map-type>
              <name>tls-test</name>
            </cert-to-name>
          </cert-maps>
        </client-auth>
      </tls>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>

where 172.18.0.2 is OB-BAA ip address.

After above confiuration device simulator is not getting aligned in OB-BAA and observing javax.net.ssl.SSLException: Received fatal alert:handshake_failure in
OB-BAA karaf.log. 
also [ERR]: SSL_accept failed(certificate verify failed) observed in device simulator logs.

could anyone help me please ?

**Comment by BinayKapri** [comment]
[netopeer2-cli-requests.txt](https://github.com/BroadbandForum/obbaa/files/5051852/netopeer2-cli-requests.txt)

**Comment by BinayKapri** [comment]
attaching netopeer2-cli-requests.txt

**Comment by selvaitech** [comment]
@BinayKapri , netconf-simulator.zip file has been updated. can you please help to pull the latest code and check if you are able to   connect to the device?

**Comment by BinayKapri** [comment]
@selvaitech  i have tested with latest code , still device is not getting connected and throws javax.net.ssl.SSLException:Received fatal alert:handshake_failure.
please find the karaf.log attached.
[karaf.log](https://github.com/BroadbandForum/obbaa/files/5060679/karaf.log)

**Comment by BinayKapri** [comment]
@selvaitech  i tested again and now device is getting connected successfully.
